main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Publication
    url: publication/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: CV
    url: cv/
    weight: 50
